name: opentelemetry
version: 0.14.3
description: A framework for collecting traces from applications.
homepage: https://github.com/Workiva/opentelemetry-dart
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  fixnum: '>=0.10.0 <2.0.0'
  http: ^0.11.0
  logging: '>=0.11.4 <2.0.0'
  protobuf: '>=1.1.0 <3.0.0'

dev_dependencies:
  mockito: ^4.1.0
  test: ^1.15.5
  workiva_analysis_options: ^1.0.1
